
export const GET_UNPRINTED_ORDERS = 'printOrders/GET_UNPRINTED_ORDERS';
export const GET_UNPRINTED_ORDERS_SUCCESS = 'printOrders/GET_UNPRINTED_ORDERS_SUCCESS';
export const GET_UNPRINTED_ORDERS_ERROR = 'printOrders/GET_UNPRINTED_ORDERS_ERROR';
export const PRINT_ORDERS = 'printOrders/PRINT_ORDERS';
export const PRINT_ORDERS_SUCCESS = 'printOrders/PRINT_ORDERS_SUCCESS';
export const PRINT_ORDERS_ERROR = 'printOrders/PRINT_ORDERS_ERROR';
export const RESET_STATE = 'printOrders/RESET_STATE';
