export const GET_UNFULFILLED_ORDERS = 'orders/GET_UNFULFILLED_ORDERS';
export const GET_UNFULFILLED_ORDERS_SUCCESS = 'orders/GET_UNFULFILLED_ORDERS_SUCCESS';
export const GET_UNFULFILLED_ORDERS_ERROR = 'orders/GET_UNFULFILLED_ORDERS_ERROR';
export const COMPLETE_UNFULFILLED_ORDERS_SUCCESS = 'NavBar/COMPLETE_UNFULFILLED_ORDERS_SUCCESS';
export const COMPLETE_UNFULFILLED_ORDERS_ERROR = 'NavBar/COMPLETE_UNFULFILLED_ORDERS_ERROR';
