export const CHECK_FOR_LOCAL_KEYS = 'NavBar/CHECK_FOR_LOCAL_KEYS';
export const RESTORE_KEYS_TO_STATE = 'NavBar/RESTORE_KEYS_TO_STATE';
export const SIGN_IN_START = 'NavBar/SIGN_IN_START';
export const SIGN_IN_SUCCESS = 'NavBar/SIGN_IN_SUCCESS';
export const SIGN_IN_ERROR = 'NavBar/SIGN_IN_ERROR';
export const REFRESH_KEYS = 'NavBar/REFRESH_KEYS';
export const REFRESH_KEYS_SUCCESS = 'NavBar/REFRESH_KEYS_SUCCESS';
export const REFRESH_KEYS_ERROR = 'NavBar/REFRESH_KEYS_ERROR';
export const COMPLETE_SIGN_IN_SUCCESS = 'NavBar/COMPLETE_SIGN_IN_SUCCESS';
export const COMPLETE_SIGN_IN_ERROR = 'NavBar/COMPLETE_SIGN_IN_ERROR';
export const COMPLETE_REFRESH_KEY_SUCCESS = 'NavBar/COMPLETE_REFRESH_KEY_SUCCESS';
export const COMPLETE_REFRESH_KEY_ERROR = 'NavBar/COMPLETE_REFRESH_KEY_ERROR';

