export const INITIALIZE_CREDENTIALS = 'NavBar/INITIALIZE_CREDENTIALS';
export const REFRESH_TOKEN = 'NavBar/REFRESH_TOKEN';
export const REFRESH_TOKEN_SUCCESS = 'NavBar/REFRESH_TOKEN_SUCCESS';
export const REFRESH_TOKEN_ERROR = 'NavBar/REFRESH_TOKEN_ERROR';
export const SIGN_IN = 'NavBar/SIGN_IN';
export const SIGN_IN_SUCCESS = 'NavBar/SIGN_IN_SUCCESS';
export const SIGN_IN_ERROR = 'NavBar/SIGN_IN_ERROR';
